# Cloud Build Configuration for Cotton ERP
# Project: commodity-plafform-sandbox
# 
# Triggers on: Push to main/develop branches
# Builds: Backend + Frontend Docker images
# Deploys: Cloud Run services

steps:
  # ============================================================================
  # STEP 1: Build Backend Docker Image
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/backend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/backend:latest'
      - '-f'
      - 'infra/docker/backend/Dockerfile.prod'
      - '.'
    timeout: '900s'

  # ============================================================================
  # STEP 2: Push Backend Image to Artifact Registry
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-latest'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/backend:latest'
    waitFor: ['build-backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-sha'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/backend:$SHORT_SHA'
    waitFor: ['build-backend']

  # ============================================================================
  # STEP 3: Build Frontend Docker Image (includes build + Nginx)
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend-image'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/frontend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/frontend:latest'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://backend-service-565186585906.us-central1.run.app'
      - '-f'
      - 'infra/docker/frontend/Dockerfile.prod'
      - 'frontend'
    waitFor: ['build-backend']
    timeout: '900s'

  # ============================================================================
  # STEP 4: Push Frontend Image
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-latest'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/frontend:latest'
    waitFor: ['build-frontend-image']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-sha'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/frontend:$SHORT_SHA'
    waitFor: ['build-frontend-image']

  # ============================================================================
  # STEP 5: Deploy Backend to Cloud Run (migrations run on startup)
  # ============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/backend:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--timeout=300'
      - '--concurrency=80'
      - '--port=8080'
      - '--vpc-connector=cotton-erp-connector'
      - '--set-cloudsql-instances=commodity-plafform-sandbox:us-central1:cotton-erp-db'
      - '--set-env-vars=ENVIRONMENT=sandbox,LOG_LEVEL=INFO,GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets=DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest,JWT_SECRET_KEY=jwt-secret:latest,OPENAI_API_KEY=openai-key:latest,HF_TOKEN=huggingface-token:latest'
      - '--service-account=backend-runtime@$PROJECT_ID.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--cpu-boost'
      - '--no-cpu-throttling'
    waitFor: ['push-backend-sha']
    timeout: '600s'

  # ============================================================================
  # STEP 6: Deploy Frontend to Cloud Run
  # ============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/frontend:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--port=80'
      - '--allow-unauthenticated'
    waitFor: ['push-frontend-sha', 'push-frontend-latest']
    timeout: '300s'

  # ============================================================================
  # STEP 7: Health Check (Authenticated with Identity Token)
  # ============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running authenticated health check..."
        TOKEN=$$(gcloud auth print-identity-token --audience=https://backend-service-565186585906.us-central1.run.app)
        curl -X GET \
            -H "Authorization: Bearer $$TOKEN" \
            https://backend-service-565186585906.us-central1.run.app/health
    waitFor: ['deploy-backend']

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  # dynamicSubstitutions: true  # Disabled for manual builds

# Timeout for entire build
timeout: 1800s

# Images to store in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/backend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/backend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/frontend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cotton-erp/frontend:latest'
# Cloud Build needs secretmanager.secretAccessor role
