"""your-change

Revision ID: 22989daa29de
Revises: f1d199e8ab02
Create Date: 2025-11-19 15:26:34.978063

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '22989daa29de'
down_revision = 'f1d199e8ab02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
