"""noop-check-after-fix

Revision ID: f1d199e8ab02
Revises: 32c4005785a7
Create Date: 2025-11-19 15:26:19.713708

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f1d199e8ab02'
down_revision = '32c4005785a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
